# Naive Bayes Classifier

In [105]:
import numpy as np
import pandas as pd
data = pd.read_csv('PlayTennis.csv')

In [106]:
data.shape

(14, 5)

In [107]:
data

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [108]:
# Training  
# Lookup Table(Dictionary) 
# Testing

In [109]:
# P(Yes) and P(No)

In [110]:
data['play'].value_counts()

play
yes    9
no     5
Name: count, dtype: int64

In [111]:
PYes = 9/14
PNo = 5/14
print(PYes)
print(PNo)

0.6428571428571429
0.35714285714285715

In [112]:
# Outlook
pd.crosstab(data['outlook'],data['play'])

play      no  yes
outlook
overcast   0    4
rainy      2    3
sunny      3    2

In [113]:
POvercastNo = 0
PRainyNo = 2/5
PSunnyNo = 3/5

POvercastYes = 4/9
PRainyYes = 3/9
PSunnyYes = 2/9

In [114]:
# temp
pd.crosstab(data['temp'],data['play'])

play  no  yes
temp
cool   1    3
hot    2    2
mild   2    4

In [115]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [116]:
# Humidity
pd.crosstab(data['humidity'],data['play'])

play      no  yes
humidity
high       4    3
normal     1    6

In [117]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [118]:
# Wind
pd.crosstab(data['windy'],data['play'])

play   no  yes
windy
False   2    6
True    3    3

In [119]:
# False=Weak, True=Strong
PWeakNo = 2/5
PStrongNo = 3/5

PWeakYes = 6/9
PStrongYes = 3/9

In [120]:
# Problem 1

# Outlook=sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

# Solution -

# P(Yes / Sunny,Hot,High,Weak) = P(Sunny/Yes) * P(Hot/Yes) * P(High/Yes) * P(Weak/Yes) * P(Yes)
# P(No / Sunny,Hot,High,Weak) = P(Sunny/No) * P(Hot/No) * P(High/No) * P(Weak/No) * P(No)

#compare and decide using the maximum a posteriori rule

In [121]:
Play_Yes = PSunnyYes * PHotYes * PHighYes * PWeakYes * PYes
print(Play_Yes)

0.007054673721340387

In [122]:
No_Play = PSunnyNo * PHotNo * PHighNo * PWeakNo * PNo
print(No_Play)

0.02742857142857143

In [123]:
# Hence No play in Problem 1

In [124]:
# Problem 2

# Outlook=Overcast, Temp=Cool, Humidity=Normal, Wind=Weak
# Play or No Play?

# Solution -

# P(Yes / Overcast,Cool,Normal,Weak) = P(Overcast/Yes) * P(Cool/Yes) * P(Normal/Yes) * P(Weak/Yes) * PYes
# P(No / Overcast,Cool,Normal,Weak) = P(Overcast/No) * P(Cool/No) * P(Normal/No) * P(Weak/No) * PNo

#compare and decide using the maximum a posteriori rule

In [125]:
Play_Yes_day = POvercastYes * PCoolYes * PNormalYes * PWeakYes * PYes
print(Play_Yes_day)

0.042328042328042326

In [126]:
No_Play_day = POvercastNo * PCoolNo * PNormalNo * PWeakNo * PNo
print(No_Play_day)

0.0

In [127]:
# Hence He will Play on Problem 2